// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJumJxsvqOcEDOgAOQ6DvxPZNGQaY53g',
    appId: '1:578288858034:web:73ed7c6b9af40b40486aab',
    messagingSenderId: '578288858034',
    projectId: 'healtrack-2a168',
    authDomain: 'healtrack-2a168.firebaseapp.com',
    storageBucket: 'healtrack-2a168.firebasestorage.app',
    measurementId: 'G-XP5MN69HLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOpV_d85rsKDBC6k-BXEHSNzxF7pEBZQ',
    appId: '1:578288858034:android:0783de8eed24e46f486aab',
    messagingSenderId: '578288858034',
    projectId: 'healtrack-2a168',
    storageBucket: 'healtrack-2a168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-pn_2fjbPWJZyNk_BaDiuBe4e0Jhh70',
    appId: '1:578288858034:ios:c062e4f8e2fe3ffe486aab',
    messagingSenderId: '578288858034',
    projectId: 'healtrack-2a168',
    storageBucket: 'healtrack-2a168.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX-pn_2fjbPWJZyNk_BaDiuBe4e0Jhh70',
    appId: '1:578288858034:ios:c062e4f8e2fe3ffe486aab',
    messagingSenderId: '578288858034',
    projectId: 'healtrack-2a168',
    storageBucket: 'healtrack-2a168.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoJumJxsvqOcEDOgAOQ6DvxPZNGQaY53g',
    appId: '1:578288858034:web:9c9cff852f877f08486aab',
    messagingSenderId: '578288858034',
    projectId: 'healtrack-2a168',
    authDomain: 'healtrack-2a168.firebaseapp.com',
    storageBucket: 'healtrack-2a168.firebasestorage.app',
    measurementId: 'G-BFZVCTY3CN',
  );
}
